export const HIDE_DOCREPO_HEADER_PANEL = 'HIDE_DOCREPO_HEADER_PANEL';
export const HIDE_DOCREPO_CATEGORY_PANEL = 'HIDE_DOCREPO_CATEGORY_PANEL';
export const HIDE_DOCREPO_DETAILS_PANEL = 'HIDE_DOCREPO_DETAILS_PANEL';
export const HIDE_DOCREPO_FOOTER_PANEL = 'HIDE_DOCREPO_FOOTER_PANEL';
export const FETCH_DOCREPO_SUCCESS = 'FETCH_DOCREPO_SUCCESS';





