export const SET_DISPLAY_MESSAGE = 'SET_DISPLAY_MESSAGE';
export const HIDE_CONTROL_PANEL = 'HIDE_CONTROL_PANEL';
export const HIDE_OPTIONS_PANEL = 'HIDE_OPTIONS_PANEL';
export const HIDE_NAVIGATION_PANEL = 'HIDE_NAVIGATION_PANEL';
export const HIDE_BOTTOM_PANEL = 'HIDE_BOTTOM_PANEL';
export const INCREMENT_SURVEY_INDEX = 'INCREMENT_SURVEY_INDEX';
export const DECREMENT_SURVEY_INDEX = 'DECREMENT_SURVEY_INDEX';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const SURVEY_FETCH_SUCCESS = 'SURVEY_FETCH_SUCCESS';
export const DISPLAY_SURVEY_QUESTIONS = 'DISPLAY_SURVEY_QUESTIONS';
export const DISPLAY_QUESTIONS = 'DISPLAY_QUESTIONS';
export const DISPLAY_START_MESSAGE = 'DISPLAY_START_MESSAGE';
export const DISPLAY_END_MESSAGE = 'DISPLAY_END_MESSAGE';
export const SURVEY_ENDED = 'SURVEY_ENDED';
export const REGISTER_RESPONSE='REGISTER_RESPONSE';
export const DEREGISTER_RESPONSE='DEREGISTER_RESPONSE';
export const HIDE_NOTIFICATIONS_PANEL = 'HIDE_NOTIFICATIONS_PANEL';
export const DISPLAY_QUESTIONS_PANEL = "DISPLAY_QUESTIONS_PANEL";


export const LOAD_SURVEY_SUCCESS = 'LOAD_SURVEY_SUCCESS';





