export const SET_DISPLAY_MESSAGE = 'SET_DISPLAY_MESSAGE';
export const HIDE_CONTROL_PANEL = 'HIDE_CONTROL_PANEL';
export const HIDE_OPTIONS_PANEL = 'HIDE_OPTIONS_PANEL';
export const HIDE_NAVIGATION_PANEL = 'HIDE_NAVIGATION_PANEL';
export const HIDE_BOTTOM_PANEL = 'HIDE_BOTTOM_PANEL';

